### ISSUE TITLE
How to include in my nix config?

### ISSUE THREAD

**Issue by s0undt3ch** [jla2000/lazyvim-nix#2]
Sorry for the noob question, but, how do I include this flake, and use it, in my current nix config?
Can you include examples in the readme please?

**Comment by jla2000** [comment]
That depends on your setup entirely. If you use a flake-based config you will need to add the flake to your inputs and then add the output of this flake to your packages list.

**Comment by s0undt3ch** [comment]
```nix
inputs = {
  lazyvim-nix.url = "github:jla2000/lazyvim-nix";
}
```

and then add `lazyvim-nix.packages.nvim` to the packages list?

**Comment by jla2000** [comment]
Yes

**Comment by s0undt3ch** [comment]
Thank You!
